// This file is automatically generated. Do not modify.
// This is a public configuration.
export const firebaseConfig = {
  "projectId": "streamweave-15bjq",
  "appId": "1:1032439539479:web:2b017cf7c1e756a1967952",
  "storageBucket": "streamweave-15bjq.firebasestorage.app",
  "apiKey": "AIzaSyCS4bni3VEFe0TWo_Z6rbzzHUX24FEEYS0",
  "authDomain": "streamweave-15bjq.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1032439539479"
};
